import fs from 'node:fs';
import assert from 'node:assert/strict';
import { seedTestTeam } from './browser-fixture.mjs';
const pages=await(await fetch('http://localhost:9222/json/list')).json();
const ws=new WebSocket(pages[0].webSocketDebuggerUrl);
await new Promise(r=>ws.addEventListener('open',r,{once:true}));
let serial=0;const pending=new Map(),errors=[];
ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);});
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
await send('Runtime.enable');await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
await send('Page.navigate',{url:'http://localhost:3000'});await wait(1000);
await send('Page.navigate',{url:'about:blank'});await wait(200);
await send('Storage.clearDataForOrigin',{origin:'http://localhost:3000',storageTypes:'local_storage'});
await send('Page.navigate',{url:'http://localhost:3000'});await wait(1200);
await seedTestTeam(evaluate);
assert.equal(await evaluate('document.querySelectorAll(".pitch-player").length'),7);
assert.equal(await evaluate('document.querySelectorAll(".minutes-panel th").length'),3);
assert.equal(await evaluate('document.querySelectorAll(".minutes-panel tbody tr").length'),12);
await click('[data-action="all-minutes"]');
assert.equal(await evaluate('document.querySelectorAll(".minutes-panel th").length'),7);
await click('[data-action="all-minutes"]');
assert.equal(await evaluate('document.querySelectorAll(".minutes-panel th").length'),3);
fs.mkdirSync('artifacts',{recursive:true});
fs.writeFileSync('artifacts/desktop.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
await click('[data-action="toggle"]');await wait(1200);await click('[data-action="toggle"]');
assert.ok(await evaluate('JSON.parse(localStorage.getItem("kentalla-v1")).match.elapsed')>=1);
await click('[data-action="auto-swap"]');
assert.equal(await evaluate('JSON.parse(localStorage.getItem("kentalla-v1")).match.events.length'),5);
await click('[data-action="position"]');await evaluate('document.querySelector("#position-form select").selectedIndex=1;document.querySelector("#position-form").requestSubmit()');
assert.equal(await evaluate('JSON.parse(localStorage.getItem("kentalla-v1")).match.events.length'),6);
await click('[data-action="finish"]');await click('[data-action="confirm-finish"]');
assert.equal(await evaluate('JSON.parse(localStorage.getItem("kentalla-v1")).history.length'),1);
await click('[data-action="report"]');assert.equal(await evaluate('document.querySelectorAll("dialog tbody tr").length'),12);await click('[data-action="csv"]');await click('[data-action="close"]');
await click('[data-tab="ottelu"]');await click('[data-action="new"]');
await evaluate('document.querySelector("[name=mode]").value="11";document.querySelector("#match-form").requestSubmit()');
assert.equal(await evaluate('document.querySelectorAll(".pitch-player").length'),11);
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'),true);
fs.writeFileSync('artifacts/mobile.png',Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
assert.deepEqual(errors,[]);
console.log('Browser checks passed: desktop, mobile, clock, substitution, position rotation, report, CSV action, 11v11, no runtime errors.');
await send('Page.navigate',{url:'about:blank'});await wait(200);
await send('Storage.clearDataForOrigin',{origin:'http://localhost:3000',storageTypes:'local_storage'});
ws.close();
