import { readFileSync, writeFileSync } from 'node:fs';

// A classic script also runs when index.html is opened directly with file://.
const engine = readFileSync(new URL('./engine.js', import.meta.url), 'utf8').replace(/^export /gm, '');
const app = readFileSync(new URL('./app.js', import.meta.url), 'utf8').replace(/^import .* from '\.\/engine\.js';\r?\n/, '');
writeFileSync(new URL('./browser.js', import.meta.url), `// Generated by node build.js. Edit app.js and engine.js instead.\n(() => {\n'use strict';\n${engine}\n${app}\n})();\n`);
console.log('Built browser.js');
