import assert from 'node:assert/strict';
import fs from 'node:fs';
const url=process.argv[2]||'http://localhost:3000/';
const origin=new URL(url).origin;
const pages=await(await fetch(`http://localhost:${process.env.BROWSER_DEBUG_PORT||9223}/json/list`)).json();
const ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
await new Promise(r=>ws.addEventListener('open',r,{once:true}));
let serial=0;const pending=new Map(),errors=[];
ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);});
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression:`(()=>{return eval(${JSON.stringify(expression)})})()`,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const get=()=>evaluate('JSON.parse(localStorage.getItem("kentalla-v1"))');
const point=selector=>evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);
async function touchDrag(selector,target){
 const from=await point(selector);
 await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...from,id:1}]});
 for(let i=1;i<=6;i++)await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:from.x+(target.x-from.x)*i/6,y:from.y+(target.y-from.y)*i/6,id:1}]});
 await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait(550);
}
await send('Runtime.enable');await send('Page.navigate',{url:'about:blank'});await wait(100);
await send('Storage.clearDataForOrigin',{origin,storageTypes:'local_storage'});
await send('Emulation.setDeviceMetricsOverride',{width:390,height:1100,deviceScaleFactor:1,mobile:true});
await send('Emulation.setTouchEmulationEnabled',{enabled:true});
await send('Page.navigate',{url});await wait(500);
await click('[data-action="new"]');await evaluate('document.querySelector("#match-form").requestSubmit()');
assert.equal((await get()).match.slots.filter(s=>s.id).length,0);
await click('[data-tab="kokoonpano"]');
const target=await evaluate('(()=>{const r=document.querySelector(".pitch").getBoundingClientRect();return{x:r.x+r.width*.15,y:r.y+r.height*.52}})()');
await touchDrag('[data-drag-slot="1"]',target);
let m=(await get()).match;assert.ok(Math.abs(m.slots[1].x-15)<1);assert.equal(m.slots[1].pos,'P');
await click('[data-action="position"][data-index="1"]');await click('[data-action="add-at-slot"]');
await evaluate(`const f=document.querySelector('#player-form');f.elements.name.value='Aada';f.querySelectorAll('[name=roles]').forEach(el=>el.checked=el.value==='P');f.elements.lock.value='1';f.requestSubmit()`);
m=(await get()).match;const aada=m.slots[1].id;assert.ok(aada);assert.deepEqual(m.rotationRules[aada].slots,[1]);
await click('[data-action="add-to-match"]');
await evaluate(`const f=document.querySelector('#player-form');f.elements.name.value='Bea';f.querySelectorAll('[name=roles]').forEach(el=>el.checked=el.value==='P');f.elements.lock.value='1';f.requestSubmit()`);
const bea=(await get()).players.find(p=>p.name==='Bea').id;
await touchDrag(`[data-drag-player="${bea}"]`,await point('[data-drag-slot="2"]'));
assert.equal((await get()).match.slots[2].id,null,'exact-slot lock blocks otherwise matching role');
await touchDrag(`[data-drag-player="${bea}"]`,await point('[data-drag-slot="1"]'));
assert.equal((await get()).match.slots[1].id,bea);
for(const index of [0,2,3,4]){
 await click(`[data-action="position"][data-index="${index}"]`);await click('[data-action="add-at-slot"]');
 await evaluate(`document.querySelector('#player-form [name=name]').value='Pelaaja ${index}';document.querySelector('#player-form').requestSubmit()`);
}
// Empty starter uses 5v5 for a team that has not added any players yet.
assert.equal((await get()).match.slots.filter(s=>s.id).length,5);
await click('[data-tab="ottelu"]');await click('[data-action="toggle"]');await wait(1100);await click('[data-action="toggle"]');
await click('[data-tab="kokoonpano"]');
await touchDrag(`[data-drag-player="${aada}"]`,await point('[data-drag-slot="1"]'));
m=(await get()).match;assert.equal(m.slots[1].id,aada);assert.equal(m.events.at(-1).type,'sub');assert.equal(m.events.at(-1).inId,aada);
await click('[data-action="position"][data-index="2"]');await evaluate(`document.querySelector('#position-form [name=role]').value='KH';document.querySelector('#position-form').requestSubmit()`);
assert.equal((await get()).match.slots[2].pos,'KH');
await send('Page.reload');await wait(250);await click('[data-tab="kokoonpano"]');
m=(await get()).match;assert.ok(Math.abs(m.slots[1].x-15)<1);assert.deepEqual(m.rotationRules[aada].slots,[1]);
assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await evaluate(`document.querySelector('[data-drag-player="${bea}"]').scrollIntoView({block:'center'})`);
const from=await point(`[data-drag-player="${bea}"]`);
await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...from,id:2}]});
await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:from.x,y:60,id:2}]});
await wait(1400);
const afterScroll=await point('[data-drag-slot="1"]');assert.ok(afterScroll.y>0&&afterScroll.y<844);
await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...afterScroll,id:2}]});
await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait(550);
assert.equal((await get()).match.slots[1].id,bea,'edge scrolling lets the bench player reach the field on a short phone screen');
await evaluate('window.scrollTo(0,0)');
await wait(4000);fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/lineup-mobile.png',Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
await send('Emulation.setDeviceMetricsOverride',{width:1360,height:1000,deviceScaleFactor:1,mobile:false});
fs.writeFileSync('artifacts/lineup-desktop.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
assert.deepEqual(errors,[]);
console.log('Passed real touch gestures: empty formation, move slot, add player at slot, lock rotation, reject incompatible drop, substitute from bench, role edit, reload persistence, mobile layout.');
await send('Page.navigate',{url:'about:blank'});await wait(100);await send('Storage.clearDataForOrigin',{origin,storageTypes:'local_storage'});ws.close();
