import assert from 'node:assert/strict';
import { seedTestTeam } from './browser-fixture.mjs';
const pages=await(await fetch('http://localhost:9222/json/list')).json();
const ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
await new Promise(r=>ws.addEventListener('open',r,{once:true}));
let serial=0;const pending=new Map(),errors=[];
ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);});
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression:`(()=>{return eval(${JSON.stringify(expression)})})()`,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
const get=()=>evaluate('JSON.parse(localStorage.getItem("kentalla-v1"))');
const elapse=ms=>evaluate(`window.__elapse(${ms})`);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
await send('Runtime.enable');await send('Page.enable');
await send('Page.navigate',{url:'about:blank'});await wait(100);
await send('Storage.clearDataForOrigin',{origin:'http://localhost:3000',storageTypes:'local_storage'});
const injected=await send('Page.addScriptToEvaluateOnNewDocument',{source:`
  const realDate=Date.now.bind(Date), realPerf=performance.now.bind(performance); let offset=0;
  Date.now=()=>realDate()+offset;
  Object.defineProperty(performance,'now',{value:()=>realPerf()+offset});
  window.__elapse=ms=>{offset+=ms;document.dispatchEvent(new Event('visibilitychange'));};
  if(navigator.wakeLock)Object.defineProperty(navigator.wakeLock,'request',{value:()=>Promise.reject(new Error('Simulated battery saving'))});
`});
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
await send('Page.navigate',{url:'http://localhost:3000'});await wait(500);
await seedTestTeam(evaluate);
await click('[data-action="new"]');
await evaluate(`const f=document.querySelector('#match-form');f.elements.mode.value='5';f.elements.duration.value='20';f.elements.periods.value='2';f.elements.interval.value='2';f.querySelectorAll('[name=roster]').forEach((el,i)=>el.checked=i<9);f.requestSubmit();`);
await click('[data-action="toggle"]');await click('[data-tab="kokoonpano"]');await elapse(120000);
assert.ok(await evaluate('document.querySelector("#toast").textContent.includes("Vaihdon aika")'),'reminder is shown while viewing the lineup');
await click('[data-tab="ottelu"]');
let m=(await get()).match;assert.ok(m.elapsed>=120&&m.elapsed<122);assert.equal(m.period,1);
assert.equal(await evaluate('document.querySelectorAll(".swap-group .swap-players").length'),4);
await click('[data-action="auto-swap"]');await elapse(30000);
assert.equal((await get()).match.events.length,4);
await click('[data-action="undo"]');m=(await get()).match;
assert.equal(m.events.length,0);assert.ok(m.roster.slice(0,5).every(id=>Math.abs(m.stats[id].total-m.elapsed)<.01));
await click('[data-action="toggle"]');const paused=(await get()).match.elapsed;await elapse(600000);assert.equal((await get()).match.elapsed,paused);
await click('[data-action="toggle"]');
const nextBefore=(await get()).match.nextSub;await click('[data-action="settings"]');
await evaluate('document.querySelector("#match-form").requestSubmit()');assert.equal((await get()).match.nextSub,nextBefore,'saving a team name must not postpone the rotation');
await click('[data-action="participants"]');m=(await get()).match;const injured=m.slots[1].id;
await click(`[data-action="availability"][data-id="${injured}"]`);await click('[data-action="close"]');
await elapse(30000);m=(await get()).match;assert.equal(m.slots[1].id,null);assert.ok(m.unavailable.includes(injured));
const replacement=m.roster.find(id=>!m.slots.some(s=>s.id===id)&&!m.unavailable.includes(id));
await click('[data-action="position"][data-index="1"]');
await evaluate(`document.querySelector('#position-form select').value=${JSON.stringify(replacement)};document.querySelector('#position-form').requestSubmit()`);
assert.equal((await get()).match.slots[1].id,replacement);
await click('[data-action="participants"]');await evaluate('document.querySelector("#join-form").requestSubmit()');await click('[data-action="close"]');assert.equal((await get()).match.roster.length,10);
await click('[data-action="manual-swap"]');m=(await get()).match;
const bench=m.roster.filter(id=>!m.slots.some(s=>s.id===id)&&!m.unavailable.includes(id));
const count=m.events.length;
await evaluate(`const f=document.querySelector('#swap-form');[...f.elements].filter(el=>el.tagName==='SELECT').forEach((el,i)=>el.value=i<2?${JSON.stringify(bench[0])}:'');f.requestSubmit();`);
assert.equal(await evaluate('document.querySelector("#dialog").open'),true);assert.equal((await get()).match.events.length,count,'duplicate incoming players rejected');
await evaluate(`document.querySelectorAll('#swap-form select')[1].value=${JSON.stringify(bench[1])};document.querySelector('#swap-form').requestSubmit()`);
assert.equal((await get()).match.events.length,count+2);
const countAfter=(await get()).match.events.length;
await evaluate(`document.querySelector('[data-action="auto-swap"]').dispatchEvent(new MouseEvent('click',{bubbles:true,detail:2}))`);
assert.equal((await get()).match.events.length,countAfter,'second click of a double-click is ignored');
await elapse(3600000);m=(await get()).match;assert.equal(m.elapsed,600);assert.equal(m.running,false);assert.equal(m.intermission,true);
assert.ok(await evaluate('document.querySelector("#toggle-clock").textContent.includes("2.")'));
await elapse(900000);assert.equal((await get()).match.elapsed,600);
await click('[data-action="toggle"]');assert.equal((await get()).match.period,2);
await elapse(600000);m=(await get()).match;assert.equal(m.elapsed,1200);assert.equal(m.finished,true);assert.equal((await get()).history.length,1);
await click('[data-tab="raportit"]');await click('[data-action="report"]');
const rows=await evaluate('document.querySelectorAll("dialog tbody tr").length');assert.equal(rows,10);
const copy=await evaluate('document.querySelector("dialog").textContent');assert.ok(copy.includes('pois käytöstä'));assert.ok(copy.includes('saapui otteluun'));
await click('[data-action="close"]');await click('[data-tab="ottelu"]');
assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);
assert.deepEqual(errors,[]);
console.log('Field workflow passed: 2 x 10 minutes, four-player group, undo accounting, pause, unchanged reminder, injury, empty-slot replacement, late arrival, duplicate rejection, double-click guard, halftime, full time, report, mobile layout, wake-lock denial.');
await send('Page.removeScriptToEvaluateOnNewDocument',{identifier:injected.identifier});
await send('Page.navigate',{url:'about:blank'});await wait(100);await send('Storage.clearDataForOrigin',{origin:'http://localhost:3000',storageTypes:'local_storage'});ws.close();
