import assert from 'node:assert/strict';
const pages=await(await fetch('http://localhost:9222/json/list')).json();
const ws=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
await new Promise(r=>ws.addEventListener('open',r,{once:true}));
let n=0;const pending=new Map(),errors=[];
ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)(m.result);pending.delete(m.id);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);});
const send=(method,params={})=>new Promise(resolve=>{const id=++n;pending.set(id,resolve);ws.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const get=()=>evaluate('JSON.parse(localStorage.getItem("kentalla-v1"))');
await send('Runtime.enable');await send('Page.navigate',{url:'about:blank'});await wait(100);
await send('Storage.clearDataForOrigin',{origin:'http://localhost:3000',storageTypes:'local_storage'});
await send('Page.navigate',{url:'http://localhost:3000'});await wait(1100);
assert.equal((await get()).players.length,0);assert.equal((await get()).match,null);
await click('[data-action="setup-players"]');
await evaluate(`document.querySelector('#player-form [name=name]').value='Oma pelaaja';document.querySelector('#player-form').requestSubmit()`);
await send('Page.reload');await wait(200);assert.equal((await get()).players.length,1);assert.equal((await get()).players[0].name,'Oma pelaaja');
await click('[data-tab="pelaajat"]');await click('[data-action="edit-player"]');await click('[data-action="delete-player"]');assert.equal((await get()).players.length,0);
await evaluate(`(()=>{for(let i=1;i<=5;i++){document.querySelector('[data-action="add-player"]').click();const f=document.querySelector('#player-form');f.elements.name.value='Oma '+i;f.requestSubmit();}})()`);
await click('[data-action="new"]');assert.equal(await evaluate('document.querySelector("[name=mode]").value'),'5');await evaluate('document.querySelector("#match-form").requestSubmit()');
const own=await get();assert.equal(own.match.slots.length,5);assert.equal(own.players.length,5);
const names=['Elias','Oliver','Leo','Eino','Noel','Onni','Väinö','Aatos','Emil','Toivo','Aapo','Otso'];
const players=names.map((name,i)=>({id:'demo-'+i,name,number:i+1,weight:1}));
const match={...own.match,id:'legacy-match',mode:7,home:'Oma joukkue',away:'Vierasjoukkue',elapsed:0,running:false,events:[],stats:{},roster:players.map(p=>p.id),slots:['MV','P','P','KH','KH','H','H'].map((pos,i)=>({pos,id:players[i].id}))};
const history=[{...structuredClone(match),id:'saved-report',finished:true,elapsed:60,players:structuredClone(players)}];
const install=async data=>{await evaluate(`localStorage.setItem('kentalla-v1',${JSON.stringify(JSON.stringify(data))})`);await send('Page.reload');await wait(200);};
await install({players,match,history});assert.equal((await get()).players.length,0);assert.equal((await get()).match,null);assert.deepEqual((await get()).history,history);
const edited=structuredClone(players);edited[0].name='Oma oikea nimi';
await install({players:edited,match,history});assert.equal((await get()).players[0].name,'Oma oikea nimi');assert.equal((await get()).players.length,12);assert.equal((await get()).match.id,'legacy-match');
const used={...match,elapsed:120,stats:{'demo-0':{total:120,positions:{MV:120}}}};
await install({players,match:used,history});assert.equal((await get()).match.elapsed,120);
await click('[data-tab="pelaajat"]');await click('[data-action="clear-demo"]');
const clean=await get();assert.equal(clean.players.length,0);assert.equal(clean.match,null);assert.equal(clean.history.length,2);assert.equal(clean.history[1].elapsed,120);assert.deepEqual(clean.history[1].players,players);
await send('Page.reload');await wait(1100);assert.equal((await get()).players.length,0);assert.deepEqual(errors,[]);
console.log('Onboarding passed: empty start, own-player persistence, deletion without a match, first 5v5 match, untouched demo migration, edited-player preservation, used-demo cleanup preserving reports, reload.');
await send('Page.navigate',{url:'about:blank'});await wait(100);await send('Storage.clearDataForOrigin',{origin:'http://localhost:3000',storageTypes:'local_storage'});ws.close();
