import assert from 'node:assert/strict';
import { seedTestTeam } from './browser-fixture.mjs';
async function connect(url) {
  const ws=new WebSocket(url);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
  let n=0;const pending=new Map();
  ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)(m.result);pending.delete(m.id);}});
  const send=(method,params={})=>new Promise(resolve=>{const id=++n;pending.set(id,resolve);ws.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
  return {ws,send,evaluate,click:selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`)};
}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const pages=await(await fetch('http://localhost:9222/json/list')).json();
const a=await connect(pages.find(p=>p.type==='page').webSocketDebuggerUrl);
await a.send('Page.navigate',{url:'about:blank'});await wait(100);
await a.send('Storage.clearDataForOrigin',{origin:'http://localhost:3000',storageTypes:'local_storage'});
await a.send('Page.navigate',{url:'http://localhost:3000'});await wait(350);
await seedTestTeam(a.evaluate);
await a.click('[data-action="toggle"]');await wait(1100);
const before=await a.evaluate('JSON.parse(localStorage.getItem("kentalla-v1")).match.elapsed');
await a.send('Page.reload');await wait(350);
assert.ok(await a.evaluate('JSON.parse(localStorage.getItem("kentalla-v1")).match.elapsed')>=before);
assert.equal(await a.evaluate('JSON.parse(localStorage.getItem("kentalla-v1")).match.running'),true);
await a.click('[data-action="toggle"]');await a.click('[data-action="new"]');
await a.evaluate(`(()=>{const f=document.querySelector('#match-form');f.elements.duration.value='4';f.elements.periods.value='2';f.elements.countdown.value='true';f.requestSubmit();})()`);
assert.equal(await a.evaluate('document.querySelector("#match-clock").textContent'),'02:00');
await a.evaluate(`(()=>{const s=JSON.parse(localStorage.getItem('kentalla-v1'));const m=s.match;m.running=true;m.elapsed=119;m.lastTick=Date.now()-4000;m.stats={};for(const slot of m.slots)m.stats[slot.id]={total:119,positions:{[slot.pos]:119}};localStorage.setItem('kentalla-v1',JSON.stringify(s));})()`);
await a.send('Page.reload');await wait(350);
assert.equal(await a.evaluate('JSON.parse(localStorage.getItem("kentalla-v1")).match.elapsed'),120);
assert.equal(await a.evaluate('JSON.parse(localStorage.getItem("kentalla-v1")).match.intermission'),true);
assert.equal(await a.evaluate('document.querySelector("#match-clock").textContent'),'00:00');
const target=await a.send('Target.createTarget',{url:'http://localhost:3000'});await wait(350);
const second=(await(await fetch('http://localhost:9222/json/list')).json()).find(p=>p.id===target.targetId);
const b=await connect(second.webSocketDebuggerUrl);
await b.click('[data-tab="pelaajat"]');await b.click('[data-action="edit-player"]');
await b.evaluate(`document.querySelector('#player-form [name=name]').value='Updated in second tab';document.querySelector('#player-form').requestSubmit()`);
await wait(200);assert.equal(await a.evaluate('document.querySelector("#main").inert'),true);
await a.click('[data-action="toggle"]');
assert.equal(await b.evaluate('JSON.parse(localStorage.getItem("kentalla-v1")).match.running'),false,'stale tab cannot restart the match');
assert.equal(await b.evaluate('JSON.parse(localStorage.getItem("kentalla-v1")).players[0].name'),'Updated in second tab');
await a.send('Target.closeTarget',{targetId:target.targetId});b.ws.close();
await a.click('[data-action="reload"]');await wait(300);
assert.equal(await a.evaluate('document.querySelector("#main").inert'),false);
assert.ok(await a.evaluate('document.querySelector(".pitch").textContent.includes("Updated in second tab")'));
console.log('Resilience passed: running reload, countdown, background reload at halftime, second-tab conflict guard, latest-state recovery.');
await a.send('Page.navigate',{url:'about:blank'});await wait(100);await a.send('Storage.clearDataForOrigin',{origin:'http://localhost:3000',storageTypes:'local_storage'});a.ws.close();
